version: '3.9'

services:
    nginx:
        image: nginx:alpine
        container_name: cl-nginx
        tty: true
        restart: unless-stopped
        depends_on:
            - mysql
            - react
            - laravel
        networks:
            - public
        ports:
            - 8040:80

    react:
        image: view
        build:
            context: ./view
            dockerfile: Dockerfile
        container_name: cl-react
        restart: always
        ports:
            - 4000:5000
        env_file:
            - ./view/.env.development
        volumes:
            - ./view:/app
        stdin_open: true
        tty: true
        networks:
            - sail
            - public

    laravel:
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        container_name: cl-laravel
        image: sail-8.1/app
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 4500:80
            - 4600:8080
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - ./api:/var/www/html
        networks:
            - sail
            - public
        depends_on:
            - mysql
            - redis
            - meilisearch
            - selenium

    mysql:
        image: mysql/mysql-server:8.0
        container_name: cl-mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: client_list
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        env_file:
            - ./api/.env
        volumes:
            - sail-mysql:/var/lib/mysql
            - ./api/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p password" ]
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        container_name: cl-redis
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - sail-redis:/data
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: cl-phpmyadmin
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: password
        restart: always
        ports:
            - 4550:80
        networks:
            - sail

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: cl-meilisearch
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - sail-meilisearch:/data.ms
        networks:
            - sail
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--spider",
                    "http://localhost:7700/health"
                ]
            retries: 3
            timeout: 5s

    mailhog:
        image: mailhog/mailhog:latest
        container_name: cl-mailhog
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

    selenium:
        container_name: cl-selenium
        image: selenium/standalone-chrome
        volumes:
            - /dev/shm:/dev/shm
        networks:
            - sail
networks:
    sail:
        driver: bridge
    public:


volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
